services:
  prep_container:
    image: busybox:latest
    command: "./prep.sh"
    volumes:
      - ./data:/data
      - ./prep.sh:/prep.sh
  postgres:
    image: postgres:alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      # - db-data:/var/lib/postgresql/data
      - ./data/postgres/:/var/lib/postgresql/data
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  prometheus:
    depends_on:
      - prep_container
    image: prom/prometheus:latest
    restart: always
    volumes: 
      - ./data/prometheus/:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
