[package]
name = "metrics-api"
version.workspace = true
edition.workspace = true

[dependencies]
# axum = "0.7.5"
tokio = { workspace = true }
# tower = "0.4.13"
reqwest = { workspace = true }
actix-web = "4"
