[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.11", features = ["derive", "string"] }
controller = { path="../controller" }
reqwest = { workspace = true, features = ["blocking"] }
