# runs = 1 # default
[[experiments]]
name = "localhost-experiment"
description = "Testing the functionality of the software completely using localhost"
kind = "localhost-result"
[[experiments.setup]]
runners = ["runner1"]
scripts = ["./scripts/test-setup.sh"]
[[experiments.teardown]]
runners = ["runner1"]
scripts = ["./scripts/test-teardown.sh"]
[[experiments.jobs]]
name = "test-job"
runner = "runner1"
execute = "./scripts/actual-work.sh"
arguments = 0
exporters = ["test-exporter"]
