name = "localhost-experiment"
description = "Testing the functionality of the software completely using localhost"
kind = "localhost-result"
execute = "./scripts/actual-work.sh"
arguments = 1
runners = ["runner1"]
# Optional, defaults to 1
runs = 1

[[setup]]
runners = ["runner1"]
scripts = ["./scripts/test-setup.sh"]
[[variations]]
name = "arg 0"
arguments = 0
[[variations]]
name = "arg 1"
arguments = 1
exporters = ["test-exporter"]
[[teardown]]
runners = ["runner1"]
scripts = ["./scripts/test-teardown.sh"]
