[metrics_api]
host = "localhost"
port = 50000

[[hosts]]
name = "localhost"
address = "localhost"
infrastructure = "linux"

[[runners]]
name = "runner1"
host = "localhost"
port = 50001

[[exporters]]
name = "test-exporter"
host = "host1"
port = 9100
kind = "node"
