name: Experimentah

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal --no-self-update --target x86_64-unknown-linux-gnu

    - name: Build Experimentah and cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: "true"
    - run: |
        cargo check
        cargo test
        cargo build
